import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
  Inject,
  OnModuleInit,
} from '@nestjs/common';
import type { LoggerService } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { ConfigService } from '@nestjs/config';
import { WINSTON_MODULE_NEST_PROVIDER } from 'nest-winston';
import * as jwt from 'jsonwebtoken';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { IS_PUBLIC_KEY } from '../decorators/public.decorator';
import { JwtPayload, RequestUser } from '../types/jwt-payload.type';

@Injectable()
export class AuthGuard implements CanActivate, OnModuleInit {
  private jwks: ReturnType<typeof createRemoteJWKSet> | null = null;

  constructor(
    private readonly reflector: Reflector,
    private readonly configService: ConfigService,
    @Inject(WINSTON_MODULE_NEST_PROVIDER)
    private readonly logger: LoggerService,
  ) { }

  onModuleInit() {
    // Build JWKS endpoint from SUPABASE_URL for ES256 verification
    const supabaseUrl = this.configService.get<string>('SUPABASE_URL');
    if (supabaseUrl) {
      const jwksUrl = new URL('/auth/v1/.well-known/jwks.json', supabaseUrl);
      this.jwks = createRemoteJWKSet(jwksUrl);
      this.logger.log?.('JWKS endpoint configured: ' + jwksUrl.toString());
    }
  }

  async canActivate(context: ExecutionContext): Promise<boolean> {
    // Skip auth for @Public() endpoints
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    if (isPublic) return true;

    const request = context.switchToHttp().getRequest();
    const token = this.extractToken(request);
    if (!token) throw new UnauthorizedException('Missing authorization token');

    try {
      const payload = await this.verifyToken(token);

      // Reject tokens without exp
      if (!payload.exp) {
        throw new UnauthorizedException('Token missing expiry');
      }

      // Detect child JWT (generated by our app with role claim)
      const isChildToken =
        payload.role === 'child' ||
        payload.user_role === 'CHILD' ||
        payload.app_metadata?.role === 'CHILD';

      // Read custom claims from root level (set by custom_access_token_hook)
      // with fallback to app_metadata for backward compatibility
      const user: RequestUser = {
        sub: payload.sub,
        email: payload.email,
        role: isChildToken
          ? 'CHILD'
          : payload.user_role || payload.app_metadata?.role || 'PARENT',
        userId: isChildToken
          ? payload.parentId || payload.app_metadata?.user_id
          : payload.user_id || payload.app_metadata?.user_id,
        childId: isChildToken
          ? payload.childId || payload.app_metadata?.child_id || payload.sub
          : payload.app_metadata?.child_id,
        parentId: payload.parentId,
      };

      request.user = user;
      return true;
    } catch (error) {
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      if (error instanceof jwt.TokenExpiredError) {
        throw new UnauthorizedException('Token expired');
      }
      if (error instanceof jwt.JsonWebTokenError) {
        throw new UnauthorizedException('Invalid token');
      }
      // jose errors
      if ((error as any)?.code === 'ERR_JWT_EXPIRED') {
        throw new UnauthorizedException('Token expired');
      }
      this.logger.error?.('JWT verification failed: ' + (error as Error).message);
      throw new UnauthorizedException('Invalid token');
    }
  }

  /**
   * Try ES256 (JWKS) first, fall back to HS256 (shared secret).
   * This supports both Supabase CLI v2 (ES256) and production/older setups (HS256).
   */
  private async verifyToken(token: string): Promise<JwtPayload> {
    // Decode header to check algorithm
    const headerB64 = token.split('.')[0];
    const header = JSON.parse(
      Buffer.from(headerB64, 'base64url').toString('utf8'),
    );

    if (header.alg === 'ES256' && this.jwks) {
      // Verify with JWKS (asymmetric)
      const { payload } = await jwtVerify(token, this.jwks);
      return payload as unknown as JwtPayload;
    }

    // Fall back to HS256 with shared secret
    const secret = this.configService.get<string>('SUPABASE_JWT_SECRET');
    if (!secret) {
      this.logger.error?.(
        'SUPABASE_JWT_SECRET is not configured — check your .env file',
      );
      throw new UnauthorizedException('Authentication service unavailable');
    }
    return jwt.verify(token, secret) as JwtPayload;
  }

  private extractToken(request: any): string | null {
    const auth = request.headers?.authorization;
    if (!auth) return null;
    const [type, token] = auth.split(' ');
    return type === 'Bearer' ? token : null;
  }
}
