import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
  Inject,
} from '@nestjs/common';
import type { LoggerService } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { ConfigService } from '@nestjs/config';
import { WINSTON_MODULE_NEST_PROVIDER } from 'nest-winston';
import * as jwt from 'jsonwebtoken';
import { IS_PUBLIC_KEY } from '../decorators/public.decorator';
import { JwtPayload, RequestUser } from '../types/jwt-payload.type';

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(
    private readonly reflector: Reflector,
    private readonly configService: ConfigService,
    @Inject(WINSTON_MODULE_NEST_PROVIDER)
    private readonly logger: LoggerService,
  ) { }

  canActivate(context: ExecutionContext): boolean {
    // Skip auth for @Public() endpoints
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    if (isPublic) return true;

    const request = context.switchToHttp().getRequest();
    const token = this.extractToken(request);
    if (!token) throw new UnauthorizedException('Missing authorization token');

    try {
      const secret = this.configService.get<string>('SUPABASE_JWT_SECRET');
      if (!secret) {
        this.logger.error(
          'SUPABASE_JWT_SECRET is not configured — check your .env file',
        );
        throw new UnauthorizedException('Authentication service unavailable');
      }

      const payload = jwt.verify(token, secret) as JwtPayload;

      // Reject tokens without exp
      if (!payload.exp) {
        throw new UnauthorizedException('Token missing expiry');
      }

      // Detect child JWT (generated by our app with role claim)
      const isChildToken =
        payload.role === 'child' ||
        payload.user_role === 'CHILD' ||
        payload.app_metadata?.role === 'CHILD';

      // Read custom claims from root level (set by custom_access_token_hook)
      // with fallback to app_metadata for backward compatibility
      const user: RequestUser = {
        sub: payload.sub,
        email: payload.email,
        role: isChildToken
          ? 'CHILD'
          : payload.user_role || payload.app_metadata?.role || 'PARENT',
        userId: isChildToken
          ? payload.parentId || payload.app_metadata?.user_id
          : payload.user_id || payload.app_metadata?.user_id,
        childId: isChildToken
          ? payload.childId || payload.app_metadata?.child_id || payload.sub
          : payload.app_metadata?.child_id,
        parentId: payload.parentId,
      };

      request.user = user;
      return true;
    } catch (error) {
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      if (error instanceof jwt.TokenExpiredError) {
        throw new UnauthorizedException('Token expired');
      }
      if (error instanceof jwt.JsonWebTokenError) {
        throw new UnauthorizedException('Invalid token');
      }
      throw new UnauthorizedException('Authentication failed');
    }
  }

  private extractToken(request: any): string | null {
    const auth = request.headers?.authorization;
    if (!auth) return null;
    const [type, token] = auth.split(' ');
    return type === 'Bearer' ? token : null;
  }
}
