name: english_pro
description: AI-powered English speaking practice for Vietnamese kids
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^11.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  phosphor_flutter: ^2.1.0

dev_dependencies:
  bloc_lint: ^0.4.0
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.23
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
